/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./view/GameView"
import Seat from "./sprite/Seat"
import Abandon from "./sprite/Abandon"
import Rise from "./sprite/Rise"
import Follow from "./sprite/Follow"
import StartView from "./view/StartView"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("view/GameView.js",GameView);
		reg("sprite/Seat.js",Seat);
		reg("sprite/Abandon.js",Abandon);
		reg("sprite/Rise.js",Rise);
		reg("sprite/Follow.js",Follow);
		reg("view/StartView.js",StartView);
    }
}
GameConfig.width = 400;
GameConfig.height = 800;
GameConfig.scaleMode ="exactfit";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Game.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
