/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./view/GameView"
import Seat from "./sprite/Seat"
import Abandon from "./sprite/Abandon"
import Rise from "./sprite/Rise"
import Follow from "./sprite/Follow"
import Start from "./sprite/Start"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("view/GameView.js",GameView);
		reg("sprite/Seat.js",Seat);
		reg("sprite/Abandon.js",Abandon);
		reg("sprite/Rise.js",Rise);
		reg("sprite/Follow.js",Follow);
		reg("sprite/Start.js",Start);
    }
}
GameConfig.width = 370;
GameConfig.height = 658;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Start.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
